### ISSUE TITLE
wrong capture index

### ISSUE THREAD

**Issue by qjebbs** [valoricDe/MultiRegExp2#1]
Please look into this code:
```javascript
let str = "aaaaaaaaa";
let reg = /((a{2})a(\2))/ig;
let mreg = new MultiRegExp2(reg);
let matches = mreg.execForAllGroups(str, true);
for (let m of matches) {
    console.log(m.match, m.start, m.end);
}
```
output:
```
aaaaa 0 5
aa 0 2
aa 3 5
```
expected:
```
aaaaa 0 4
aa 0 1
aa 3 4
```

**Comment by qjebbs** [comment]
I realized that you may intentionally make the end index point to next start index, so I close this issue now.

**Comment by valoricDe** [comment]
Yeah it is intentional. As I think it would be weird to have a match like {"match":"x","start":1,"end":1}
