### ISSUE TITLE
Use generator function

### ISSUE THREAD

**Issue by valoricDe** [valoricDe/MultiRegExp2#5]

**Comment by eromoe** [comment]
Hi, I mean something like python's  `re.finditer`

> re.finditer(pattern, string, flags=0)
> Return an iterator yielding MatchObject instances over all non-overlapping matches for the RE pattern in string. The string is scanned left-to-right, and matches are returned in the order found. Empty matches are included in the result unless they touch the beginning of another match.

https://docs.python.org/2/library/re.html

In javascript, would  like

```
function* regexFindIter(re, text) {
  while ((m = re.exec(text)) !== null) {
    if (m.index === re.lastIndex) {
      re.lastIndex++;
    }

    m.forEach((match, groupIndex) => {
      yield match
    });
  }
}

```

**Comment by valoricDe** [comment]
Actually this implementation is only doing one exec. Therefore a generator function does not make much sense in this case. For getting only one Group you could call `execForGroup(string, group)`. But thanks for the suggestion anyway.
